name = "fqnovel-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-06"


[vars]
install_id = "3428753930731403"
server_device_id = "3428753930727307"
aid = "1967"
update_version_code = "62532"

[build]
command = "cargo install -q worker-build && worker-build --release"
